spring:
  application:
    name: propertyrental

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /api/v1

app:
  environment:
    isProd: ${APP_ENV_IS_PROD:false}
  security:
    rsaKeys:
      publicKey: ${APP_SECURITY_PUBLIC_KEY:classpath:certs/publicKey.pem}
      privateKey: ${APP_SECURITY_PRIVATE_KEY:classpath:certs/privateKey.pem}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

logging:
  level:
    '[com.codingplayground.propertyrental]': TRACE
    '[org.springframework.security]': DEBUG
    '[org.springframework.boot.autoconfigure.flyway]': DEBUG
